name: Update Exchange Rates

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_rate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r scripts/requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Scrape and insert rates
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python -m scripts.deploy --scrape
